version: "2"
containers:
- name: workstation
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
  - 8080
  - 8200
  - 8500
  - 443
  - 8443
  - 8558
  - 8301
  memory: 2048
gcp_projects:
- name: consul
  services:
  - container.googleapis.com
  - cloudresourcemanager.googleapis.com
  - compute.googleapis.com
  - iam.googleapis.com
  - cloudkms.googleapis.com
aws_accounts:
- name: consul
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
azure_subscriptions:
- name: consul
  roles:
  - Owner